server:
  shutdown: graceful

spring:
  application:
    name: realteeth
  lifecycle:
    timeout-per-shutdown-phase: 35s
  r2dbc:
    url: r2dbc:mysql://localhost:3306/realteeth
    username: root
    password: 1234

springdoc:
  swagger-ui:
    path: /docs
  use-fqn: true

app:
  resilience:
    circuit-breaker:
      sliding-window-size: 5
      failure-rate-threshold: 60
      wait-duration-in-open-state-seconds: 30
      permitted-number-of-calls-in-half-open-state: 1
  named-lock:
    pool-size: 5
    initial-size: 1
    max-idle-time-minutes: 10
    max-acquire-time-seconds: 30
  tooth-analysis:
    max-send-count: 5
    status-poll-interval-ms: 2000
  scheduler:
    pending-analysis:
      fixed-delay-ms: 10000
      lock-at-most-for: PT30S
    processing-analysis:
      fixed-delay-ms: 10000
      lock-at-most-for: PT30S
    task-scheduler:
      pool-size: 2
      await-termination-seconds: 35

client:
  tooth-analysis:
    base-url: https://dev.realteeth.ai/mock
    api-key: mock_78b70376b9c74449931f7622c0790f3d
